### ISSUE TITLE
Google Drive Class does not have drives API for shared drive management

### ISSUE THREAD

**Issue by saurav28** [googleworkspace/java-samples#184]
# Summary

Google Drive Class does not have drives API for shared drive management.

## Sample Name

Drives snippets list the drives api which is not present in the Google Java client APIs anymore

https://github.com/googleworkspace/java-samples/blob/39c8e0c9d7842d4d32e2452e7d210513a8e42164/drive/snippets/drive_v3/src/main/java/DriveSnippets.java#L25
There is a teamdrives API. Is this supposed to be the API for Shared Drive management.

I want to create a shared drive from service account credentials programmatically.

## Specifications

- Java version - 11
- OS Mac

**Comment by sqrrrl** [comment]
LIkely that you're using an old java client? Teamdrives were renamed to drives quite awhile ago and are present in current java libraries.
