### ISSUE TITLE
access link prompt not working when deployed on remote server

### ISSUE THREAD

**Issue by vaibhav2903** [googleworkspace/java-samples#26]
Access link prompt not working when deployed on remote server

### Expected Behavior
It was supposed to authorize when i open the link which i get in the logs on the browser
### Actual Behavior
but it was giving me 404 error after authorizing. 
### Specifications
  - Java version (`java 1.8`)
  - OS (Mac/Linux/Windows)
 - Maven

**Comment by grant** [comment]
Did you open the link with a browser with the correct G Suite access? If you access the file from an account that isn't shared with, you'll see the error 404.
Can you try opening the link with an incognito browser tab?
