### ISSUE TITLE
Test "/credentials.json" in quickstarts on Windows

### ISSUE THREAD

**Issue by asrivas** [googleworkspace/java-samples#39]

**Comment by IC088** [comment]
hi I am having this exact problem on Windows, for some reason I cannot read the json file

**Comment by pavankjadda** [comment]
Add `credentials.json` file under `resources` folder. This should work.

**Comment by dev-ns8** [comment]
I am also having this issue. Getting a `java.io.FileNotFoundException: Resource not found: /credentials.json`

I have put the JSON file in my `res` directory.  I have also tried putting the JSON file in the same directory as my `MainActivity.java` (where I attempt to open it at) and still get the same error.

I also tried to supply the full exact path to the file, still receiving a `FileNotFoundException`

Any insight would be greatly appreciated

**Comment by An571sha** [comment]
add your credentials.json inside the asset folder and use this as InputStream
`InputStream in = context.getAssets().open(CREDENTIALS_FILE_PATH);`
