### ISSUE TITLE
No export links available for google form and google map

### ISSUE THREAD

**Issue by sonam-serchan** [googleworkspace/java-samples#788]
# Summary

I am trying to export the google workspace documents. For this, I use export link from files resource to get the available download link for the document type. I can get for documents such as google doc, slide, spreadsheet etc. However, for google form, google map, I don't get the export links. Thus, cannot export the documents.

https://developers.google.com/drive/api/guides/manage-downloads#export-content-browser
<img width="873" alt="Screenshot 2024-03-06 at 10 25 46" src="https://github.com/googleworkspace/java-samples/assets/23254380/fd435e46-72fa-4260-99ea-74d155f4c567">

## Sample Name

(i.e. Java Samples)

## Expected Behavior

Get export links for google form, google map to export the document

## Actual Behavior

No export links available from files resource

## Specifications

- Java version (`java -version`) - 17
- OS (Mac/Linux/Windows) - Mac

**Comment by sqrrrl** [comment]
Thoe files are not exportable. See https://developers.google.com/drive/api/guides/ref-export-formats for supported conversions.

For forms, use the Forms & sheets APIs to export to whatever format needed.

**Comment by sqrrrl** [comment]
If you'd like to file a feature request for the API to support additional conversions, file it at https://b.corp.google.com/issues/new?component=191650&template=824106&pli=1
