### ISSUE TITLE
Error on Android google calendar project 

### ISSUE THREAD

**Issue by luc56** [googleworkspace/java-samples#90]
(Please fill out these details before submitting an issue)
System.err: java.security.KeyStoreException: JKS not found on Android Studio

  - Windows 10

**Comment by shuizi** [comment]
同样的问题

**Comment by shuizi** [comment]
> （请在提交问题之前填写这些详细信息）
> System.err：java.security.KeyStoreException：在Android Studio上找不到JKS
> 
> * Windows 10

解决了么？
